// Column indices for raw daily tabs (0-indexed)
// Col A = GMV Target (Month), Col B = Month, Col C = Date, ...
export const RAW_COLUMNS = {
  gmvTargetMonth: 0,
  month: 1,
  date: 2,
  monthlyVideoPostedPacing: 3,
  samplingPacing: 4,
  monthlyGmvPacing: 5,
  dailyTargetGmv: 6,
  cumulativeMtdGmv: 7,
  projectedMonthlyGmv: 8,
  projectedGmvDelta: 9,
  gmvPacing: 10,
  affiliatesAdded: 11,
  contentPending: 12,
  videosPosted: 13,
  monthlyVideoTarget: 14,
  videosConverted: 15,
  sparkCodesAcquired: 16,
  targetInvitesSent: 17,
  dailySampleRequests: 18,
  l0Approved: 19,
  l1Approved: 20,
  l2Approved: 21,
  l3Approved: 22,
  l4Approved: 23,
  l5Approved: 24,
  l6Approved: 25,
  totalSamplesApproved: 26,
  targetSamplesGoals: 27,
  samplesDecline: 28,
  samplesRemain: 29,
  dailyGmv: 30,
  gmvTarget: 31,
  adSpend: 32,
  spendTarget: 33,
  roi: 34,
  roiTarget: 35,
  // SKU-specific columns start at index 36
  skuStart: 36,
} as const;

// Column indices for rollup tabs (0-indexed)
// Col A = client/week label, Col B = Date, Col C onward = metrics
export const ROLLUP_COLUMNS = {
  weekLabel: 0,
  date: 1,
  // Metrics start at col C (index 2) — same order as raw tabs starting from monthlyVideoPostedPacing
  monthlyVideoPostedPacing: 2,
  samplingPacing: 3,
  monthlyGmvPacing: 4,
  dailyTargetGmv: 5,
  cumulativeMtdGmv: 6,
  projectedMonthlyGmv: 7,
  projectedGmvDelta: 8,
  gmvPacing: 9,
  affiliatesAdded: 10,
  contentPending: 11,
  videosPosted: 12,
  monthlyVideoTarget: 13,
  videosConverted: 14,
  sparkCodesAcquired: 15,
  targetInvitesSent: 16,
  dailySampleRequests: 17,
  l0Approved: 18,
  l1Approved: 19,
  l2Approved: 20,
  l3Approved: 21,
  l4Approved: 22,
  l5Approved: 23,
  l6Approved: 24,
  totalSamplesApproved: 25,
  targetSamplesGoals: 26,
  samplesDecline: 27,
  samplesRemain: 28,
  dailyGmv: 29,
  gmvTarget: 30,
  adSpend: 31,
  spendTarget: 32,
  roi: 33,
  roiTarget: 34,
} as const;
